green_/_users/urls.py
from django.urls import path
from . import views

app_name = '_users'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.LaunchView.as_view(), name='index'), # 'launch/<int:pk>/'
    path('login.index/', views.login_index, name='login-index'),
    path('users.login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('chgpwd.index/', views.chg_pwd, name='chgpwd-index'),
    # path('change.pass/', views.change_password, name='change-password'),
]

green_/_users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
  za_id_number = models.CharField(max_length=13, null=True, blank=True)


  class Meta:
    verbose_name_plural = 'User'

  def save(self, *args, **kwargs):
      for field_name in ['first_name', 'last_name']:
          val = getattr(self, field_name, False)
          if val:
              setattr(self, field_name, val.capitalize())
      super(User, self).save(*args, **kwargs)

  def __str__(self) -> str:
    return self.username


class UserWallet(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
  tokens = models.BigIntegerField(default=0)


  class Meta:
    ordering = ['user']
    verbose_name_plural = 'User Wallet'
        
  def __str__(self) -> str:
    # avoid [ TypeError: __str__ returned non-string (type User) ] convert to str()
    return str(self.user)

class BankAccount(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
  bank_account = models.CharField(max_length=13, null=True, blank=True)
  bank_name = models.CharField(max_length=13, null=True, blank=True)
  phone_number = PhoneNumberField(blank=True)

  class Meta:
    ordering = ['user']
    verbose_name_plural = 'Bank Accounts'

  def __str__(self) -> str:
    return str(self.user)

green_/_users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from ._redoing import validate_password

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from za_id_number.za_id_number import (
  SouthAfricanIdentityValidate, SouthAfricanIdentityNumber)

# Create the form class.
class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'za_id_number', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[str(field)].label = ''
            self.fields[str(field)].required = False
            self.fields[str(field)].help_text = None

        self.fields['first_name'].widget.attrs.update(placeholder='First name')
        self.fields['last_name'].widget.attrs.update(placeholder='Last name')
        self.fields['za_id_number'].widget.attrs.update(placeholder='Enter your ID')
        self.fields['password1'].widget.attrs.update(placeholder='Create password')
        self.fields['password2'].widget.attrs.update(placeholder='Confirm password')
    
    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if validate_password(password1) != True:
            # Add additional validation rules here
            raise forms.ValidationError(
                _(f'{validate_password(password1)}')
            )
        return password1
        
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError(
                _('The two password fields didn\'t match.')
            )
        return password2

class ChangePwdForm(forms.Form):
    username = forms.CharField(
        required=False, label=False, max_length=100, widget=forms.TextInput(
            attrs={
                'class': 'input-text with-border', 
                'placeholder': 'Enter Username'
            }
        )
    )
    za_id_number = forms.CharField(
        required=False, label=False, max_length=100, widget=forms.TextInput(
            attrs={
                'class': 'input-text with-border', 
                'placeholder': 'za_id_number'
            }
        )
    )
    create_password = forms.CharField(
        required=False, 
        label=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input-text with-border', 
                'placeholder': 'Create password'
            }
        )
    )
    confirm_password = forms.CharField(
        required=False,
        label=False,
         widget=forms.PasswordInput(
            attrs={
                'class': 'input-text with-border', 
                'placeholder': 'Confirm password'
            }
        )
    )

green_/_users/views.py
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.template import loader
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from .models import User, UserWallet
import datetime
import random
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from za_id_number.za_id_number import (
  SouthAfricanIdentityValidate, SouthAfricanIdentityNumber)

from ._redoing import validate_password, create_username
from django.db.models import Q

from .forms import NewUserForm, ChangePwdForm

# Check for users that took 12months without login and Delete the account 
try:
  nw = datetime.date.today().month
  for i in User.objects.all():
    if nw - i.last_login.month == 12:
      if i.is_superuser is False or i.is_staff is False:
        i.delete()
except:
  False


class LaunchView(View):
  def get(self, request):
    form = NewUserForm()
    return render(
       request,
      '_users/_index.html',
     {
        'form': form
     }
    )

  def post(self, request):
    form = NewUserForm(request.POST)
    za_id_number = form['za_id_number'].value()
    first_name = form['first_name'].value()
    last_name = form['last_name'].value()
    if SouthAfricanIdentityValidate(za_id_number).valid:
        if SouthAfricanIdentityNumber(za_id_number).age >= 18:
            _user =  User.objects.filter(
                za_id_number=za_id_number,
                is_active=True,
                is_staff=False,
                is_superuser=False
            )
            if not _user:
                if form.is_valid():
                    username = create_username(first_name, last_name, User)
                    form.instance.username = username
                    form.save()
                    psw = form.cleaned_data['password1']
                    user = authenticate(
                        request, username=username, password=psw
                    )
                    if user.is_authenticated:
                        login(request, user)
                        messages.success(request, f'Wellcome to _green {first_name.capitalize()}') # return 
            else: messages.info(request, f'Hi {first_name.capitalize()} {last_name.capitalize()} you already have an Account')
        else: messages.warning(request, 'You must be 18 or older to register')
    else: messages.warning(request, 'Invalid ZA/RSA ID number')
    return render(
       request,
      '_users/_index.html',
     {
        'form': form
     }
	)

def login_index(request):
    context = {}
    return render(request, '_users/_login.html', context)

def login_user(request):
   pass
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         try:
#             user = authenticate(request, username=username, password=password)
#             if user.is_authenticated:
#                 if user.is_superuser == True:
#                     login(request, user)
#                     return HttpResponseRedirect(reverse('_fundraiser:admin-index'))
#                 elif user.is_staff == True:
#                     login(request, user)
#                     #return HttpResponseRedirect(reverse(''))
#                 elif user:
#                     login(request, user)
#                     return HttpResponseRedirect(reverse('_fundraiser:account-index'))
#         except:
#             invalid = True
#             return render(
#                 request,
#                 'login_.html',
#                 {
#                     'login_context': invalid,
#                 },
#             )
#     return HttpResponseRedirect(reverse('_splash:splash-view'))

# Logout user
def logout_view(request):
  logout(request)
  i = 'Logged Out'
  messages.info(request, f'{ i }')
  return HttpResponseRedirect(reverse('_users:index'))

# def chg_pwd(request):
#     form = ChangePwdForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'chg_pwd_.html', context)

# # Change password
# def change_password(request):
#     if request.method == 'POST':
#         form = ChangePwdForm(request.POST)
#         _usename = request.POST['username']
#         _zaID = request.POST['za_id_number']
#         _password = request.POST['create_password']
#         _confirmPwd = request.POST['confirm_password']
#         if validate_password(request.POST['create_password']) == True:
#             if _password == _confirmPwd:
#                 if NewUser.objects.filter(username=_usename, za_id_number=_zaID).exists():
#                     _user = NewUser.objects.filter(username=_usename).get()
#                     new_password = _password
#                     _user.set_password(new_password)
#                     _user.save()
#                     messages.success(request, 'Password has been successfully changed')
#                 else:
#                     messages.warning(request, 'Invalid username/za_id_number')
#                     context = {'form': form}
#                     return render(request, 'chg_pwd_.html', context)
#             else:
#                 messages.warning(request, 'Passwords don\'t match')
#                 context = { 'form': form}
#                 return render(request, 'chg_pwd_.html', context)
#         else:
#             messages.warning(request, f'{validate_password(_password)}')
#             context = {'form': form}
#             return render(request, 'chg_pwd_.html', context)
#     return HttpResponseRedirect(reverse('_splash:chgpwd-index'))

green_/_users/templates/_users/_index.html
{% extends 'C:\Users\Romeo\Desktop\Easy\_green\_green-project\green_\templates\_base.html' %}
{% load static %}

{% block title %}
    _RC
{% endblock %}

{% block head %}
  <section class='head'>
    <h1>Logo</h1>
  </section>
{% endblock %}

{% block content %}
  <section class='task register' id='register'>
    <form name='registerForm' class='newuser-form'
      action='{% url "_users:index" %}' method='post'>
      {% csrf_token %}
      <h1>Account Register</h1>
      {% for field in form %}
        <div class='form-control {% if field.errors %}errors{% endif %}'>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
      <div class='confirm-box' id='registerConfirmbox'>
        <p>Please verfiy details before submiting.</p>
        <hr>
        <button type='submit' name='submit'>submit</button>
        <button type='button' name='cancel' class='cancel'>&#9747</button>
      </div>
      <button type='button' name='register'>Register</button> 
    </form>
  </section>

  <section class='task about'>
    <h1>About</h1>
    <p>
      Info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------n
    </p>
  </section>
{% endblock %}

{% block context-container %}
  <section id='regPswRequirementsBox'>
    <h3>Password must contain the following:</h3>
    <p id='registerLength' class='invalid'>Minimum 8 characters</p>
    <p id='registerLowercase' class='invalid'>Lowercase letter</p>
    <p id='registerUppercase' class='invalid'>Uppercase letter</p>
    <p id='registerSplcharacter' class='invalid'>Special character /[`!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/g</p>
    <p id='registerNumber' class='invalid'>A number</p>
  </section>
{% endblock %}

{% block footer %}
  <section class='footer navbar'>
    <a href='{% url "_users:login-index" %}'>Login</a>
    <button class='navB'>Button</button>
    <!-- <button class='navB' id='bRegister' data-page='register'>Register</button>  -->
  </section>
{% endblock %}

green_/_users/templates/_users/_login.html
{% extends 'C:\Users\Romeo\Desktop\Easy\_green\_green-project\green_\templates\_base.html' %}
{% load static %}

{% block head %}
  <section class='head'>
    <h1>Logo</h1>
  </section>
{% endblock %}

{% block content %}
  <section class='login task login-task1' id='login'>
    {% if login_context %}
      <div id='context'>
        <p><b>Invalid Login Credentials!</b></p>
      </div>
    {% endif %}
    <form name='loginForm' 
    action='{% url "_users:login" %}' method='post'>
      {% csrf_token %}
      <h1>Login</h1>
      <p>
      <input
      type='text'
      name='username'
      placeholder='Enter Username '>
      </p>
      <p>
      <input
      type='password'
      name='password'
      placeholder='Password'> 
      </p>
      <p id='shwpswloginform'>show password</p> 
      <button type='submit' name='submit' >login</button>
      <a href='/'><button type='button' class='cancel'>close</button></a>
    </form>
  </section>
{% endblock %}

{% block footer %}
  <section class='footer navbar'>
    <a href=''>Link</a>
    <button class='navB' id='bLogin' data-page='login'>Button</button>
    <!-- <button class='navB' id='bRegister' data-page='register'>Register</button>  -->
  </section>
{% endblock %}

green_/_users/templates/_users/lyt_.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}
      {% endblock %}
    </title>
    <link rel="shortcut icon" type="img/jpg" href="{% static 'FLG.jpg' %}">
    <link rel="stylesheet" type="text/css" href="{% static '_style3.css' %}">

    {% if messages %}
      <div class='msg-container' id='msgbox'>
        <div class='message'>
          {% for message in messages %}
            <span id='closemsgbox'>&#9747</span>
            <p {% if message.tags %} class='{{ message.tags }} msg'{% endif %}>
              {{ message }}
            </p>
          {% endfor %}
        </div>
        <script src='static/msg_2.js'></script>
      </div>
    {% endif %}

  </head>
  <body>
    <section class='top-container'>
      {%  block head %}
      {% endblock %}
    </section>
    
    <section class='content-grid-container'>
      {% block content %}
      {% endblock %}
    </section>

    <section id='contextcontainer' class='context-container'>
      {% block context-container %}
      {% endblock %}
    </section>

    <section class='footer-container'>
      {% block footer %}
      {%  endblock %}
    </section>
  </body>
  <script src='static/js_3.js'></script>
</html>